/* tslint:diable */
// @ts-nocheck
const { writeFile, existsSync, mkdirSync } = require('fs');
const yargs = require('yargs/yargs');
const { hideBin } = require('yargs/helpers');
const argv = yargs(hideBin(process.argv)).argv;

require('dotenv').config();
const environment = process.env.ENVIRONMENT;
const envPath = './src/environments/environment.ts';

function writeFileUsingFS(targetPath, environmentFileContent) {
  writeFile(targetPath, environmentFileContent, function (err) {
    if (err) {
      console.log(err);
    }

    if (environmentFileContent !== '') {
      console.log(`wrote variables to ${targetPath}`);
    }
  });
}

const envDirectory = './src/environments';

if (!existsSync(envDirectory)) {
  mkdirSync(envDirectory);
}

writeFileUsingFS(envPath, '');

const environmentFileContent = `
  // This file was autogenerated by dynamically running setEnv.ts and using
  // dotenv for managing API key secrecy
  export const environment = {
    production: true,
    TWITCH_CLIENT_ID: '${process.env.TWITCH_CLIENT_ID}',
    TWITCH_CLIENT_SECRET: '${process.env.TWITCH_CLIENT_SECRET}'
  };
`;

writeFileUsingFS(envPath, environmentFileContent);
/* tslint:enable */
